//
// Created by piotrek on 15.01.17.
//

#ifndef TRAVELLINGSALESMAN_CROSSOVERSTRATEGY_H
#define TRAVELLINGSALESMAN_CROSSOVERSTRATEGY_H
enum CrossoverStrategy{
    ONEPOINT,TWOPOINT,RANDOM
};
#endif //TRAVELLINGSALESMAN_CROSSOVERSTRATEGY_H
