//
// Created by piotrek on 15.01.17.
//

#ifndef TRAVELLINGSALESMAN_SELECTIONSTRATEGY_H
#define TRAVELLINGSALESMAN_SELECTIONSTRATEGY_H

enum SelectionStrategy{
    TOURNAMENT, ROULETTE
};

#endif //TRAVELLINGSALESMAN_SELECTIONSTRATEGY_H
